language: ruby
rvm:
  - 2.2

script:
  bin/rake db:migrate RAILS_ENV=test;
  bundle exec rspec

addons:
  code_climate:
    repo_token:
      secure: a/6UxyXB+RI367r+WLNzSx2KfdV1rNmlyfsq3mPzoZe5IiN8YRFIaFbi56GwFEfqMrdLOO4JnwoTmTavz6C7jOn+NYYxlX0qrCUZ/Wr1O1IS3n4qa62nQRVF3mQ1p47zqGGrY4qqudRioavU6v3mgmb14glQR9pOArg0XL8uXsEt01/jNN7BZJiWByFXJAxzQmLK1eCf5RKAkXN0HstJgj++c4PyNpwzweFTDddTTocnwhObBP3L8vH64eRkcQLhHVP8fRi2pljfSopw+Dn4vSGf0225YEc05dVD1G8hX2dmmTBOQBBQLxC/4q9aU7YSjORsHy17dyTELK/pD+INIvQVVwr6WVUz1RfZQ8tJQomNPG7umEm0/Pi7SabAoGdoXoHXGpVvUdF5BfvyEB19cSDG2X7tUHby5Zvk3kzkYXJPw2gBqwkdmuImRUImahBcAhFyjdLrwR+zuw9aq1tiNxkemw/AUI+Cfz16EONzC3lMiXYF071lApVU2QS/PT0XMlLlwkYcRPgAFOdweYCp0ZQ+xdo1O1whF0mrG4aTFC9MU4tsxxm4BmVDL/dIRyk0Pw6YLcCC0FNYp2bW28zglRJO3aKQMNsI4vHT/X3mW4Gj2ES3HnR9GZNmqNKTRmYBw2q0BAZ+usD9jnsEsEdlBG9DeeTbAywabzlR7DuJhnk=